version: '3'

services:
  drosera1:
    image: ghcr.io/drosera-network/drosera-operator:latest
    container_name: drosera-node1
    ports:
      - "31313:31313"
      - "31314:31314"
    volumes:
      - drosera_data1:/data
    command: >
      node --db-file-path /data/drosera.db
      --network-p2p-port 31313
      --server-port 31314
      --eth-rpc-url ${RPC}
      --eth-backup-rpc-url https://holesky.drpc.org
      --drosera-address 0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8
      --eth-private-key ${ETH_PRIVATE_KEY}
      --listen-address 0.0.0.0
      --network-external-p2p-address ${VPS_IP}
      --disable-dnr-confirmation true
    restart: always

  drosera2:
    image: ghcr.io/drosera-network/drosera-operator:latest
    container_name: drosera-node2
    ports:
      - "31315:31313"
      - "31316:31314"
    volumes:
      - drosera_data2:/data
    command: >
      node --db-file-path /data/drosera.db
      --network-p2p-port 31313
      --server-port 31314
      --eth-rpc-url ${RPC}
      --eth-backup-rpc-url https://holesky.drpc.org
      --drosera-address 0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8
      --eth-private-key ${ETH_PRIVATE_KEY2}
      --listen-address 0.0.0.0
      --network-external-p2p-address ${VPS_IP}
      --disable-dnr-confirmation true
    restart: always

volumes:
  drosera_data1:
  drosera_data2:
